# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BrewCoffee_Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(max_length=1024, null=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(null=1),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='BrewCoffee_Core.ProductSize'),
        ),
    ]
